services:
  mysql:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=root12345
    ports:
      - 23306:3306
  phpmyadmin:
      image: phpmyadmin
      ports:
        - 8100:80
      environment:
        - PMA_HOST=mysql
        - PMA_ARBITRARY=1
      depends_on:
        - mysql
volumes:
  db-data:
